commonAnnotations:
  include.release.openshift.io/self-managed-high-availability: "true"
  include.release.openshift.io/single-node-developer: "true"

resources:
- manifests.yaml
- service.yaml

configurations:
- kustomizeconfig.yaml
