apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-baremetal-operator
  namespace: openshift-machine-api
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
